### ISSUE TITLE
Maven build doesn't use MAVEN_OPTS anymore.

### ISSUE THREAD

**Issue by amirlanesman** [heroku/heroku-buildpack-java#76] opened 2017-05-09 20:47 UTC
When using the buildpack the `MAVEN_OPTS` env-var isn't used anymore.

To reproduce:
1. set `MAVEN_OPTS` variable to anything significant for the execution of the `mvn` command.
2. check logs and see that anything that was set in the env-var wasn't used when executing `mvn`.

when I manually set the buildpack to a previous commit it works OK:
https://github.com/heroku/heroku-buildpack-java.git#7aa61682516833fa876c209c4fdd52e145a2f47d

**Comment by jkutner** [comment] 2017-05-10 09:31
Is this at build time (after a `git push`), at runtime (with a `heroku run` command), or in CI?

**Comment by amirlanesman** [comment] 2017-05-10 10:42
@jkutner It happens to me when using Codeship for CD and manually when using `git push heroku master`

**Comment by jkutner** [comment] 2017-05-10 10:44
@amirlanesman i'm actually not sure how this would have worked with 7aa61682516833fa876c209c4fdd52e145a2f47d. Can you give me an example of your `MAVEN_OPTS`? We recommend using `MAVEN_CUSTOM_OPTS` because we leverage `MAVEN_OPTS` for internal settings.

**Comment by amirlanesman** [comment] 2017-05-10 10:59
@jkutner 
`MAVEN_OPTS=-Dproject.repo=stagingrepo -Xmx384m -Xss512k -XX:+UseCompressedOops"`
OK, I will try it now with `MAVEN_CUSTOM_OPTS`.
Thanks.

**Comment by jkutner** [comment] 2017-05-10 14:00
@amirlanesman can you clarify the following details:

* what date did this start occurring
* what was the date of your last successful deploy
* what buildpack URL you were using before it occurred
* what version of Maven you're using (if not default)
* what version of Java you're using (if not default)

I'm having a difficult time trying to reproduce this (I can't find a buildpack version that ever support `MAVEN_OPTS`), but I want to make sure I'm not overlook some kind of regression. 

Thanks!

**Comment by amirlanesman** [comment] 2017-05-10 14:58
@jkutner 

1.  started yesterday.
2. last successful deploy was 8/5.
3. I used `https://github.com/heroku/heroku-buildpack-java.git` up until I changed it to what I stated above (and as I said, with that buildpack it works for me.
4. I think it's the default but I'm not sure where it would be configured.
5. I use a `system.properties` file containing `java.runtime.version=1.8` so I guess Java 8? :)

**Comment by amirlanesman** [comment] 2017-05-11 08:30
@jkutner, with latest buildpack, even with `MAVEN_CUSTOM_OPTS` set correctly in Heroku app I can't get it to use the opts which are set there.

**Comment by jkutner** [comment] 2017-05-11 08:47
@amirlanesman are you using the Github URL, or `heroku buildpacks:set heroku/java`?

**Comment by amirlanesman** [comment] 2017-05-11 08:56
@jkutner oh, actually I'm using it with the multi buildpack `https://github.com/heroku/heroku-buildpack-multi` and setting the `.buildpacks` to:
```
https://github.com/heroku/heroku-buildpack-java.git
https://github.com/jruby/heroku-buildpack-jruby.git
```

**Comment by jkutner** [comment] 2017-05-11 09:01
@amirlanesman you are definitely right about the Github repo (`MAVEN_CUSTOM_OPTS` is broken there). You can't use the shorthand `heroku/java` in your `.buildpacks` file. But you could switch to our first-class multi buildpack support by running:

```
$ heroku buildpacks:clear
$ heroku buildpacks:add heroku/java
$ heroku buildpacks:add https://github.com/jruby/heroku-buildpack-jruby.git
```

Alternatively, you could change your `.buildpacks` file to:

```
https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/java.tgz
https://github.com/jruby/heroku-buildpack-jruby.git
```

Thanks for reporting this. I'm sorry its taken me a while to catch on.

**Comment by jkutner** [comment] 2017-05-12 13:58
This should be fixed in master

**Closed by jkutner** 2017-05-12 13:58 UTC
